browser=CHROME
headless=false
baseUrl=https://demoqa.com/login
#baseUrl=https://practicetestautomation.com/practice-test-login/


log.console=true
log.report=true
log.element.actions=true
log.wait.actions=true
screenshot.on.failure=true